FROM golang:1.14-stretch as build

LABEL maintainer="Alex Cordeiro <alexc@digitalbits.org>"

EXPOSE 5432
EXPOSE 8000

ADD . /src/ticker
WORKDIR /src/ticker
RUN go build -o /opt/digitalbits/bin/ticker ./services/ticker/

WORKDIR /src/ticker/services/ticker/docker/
RUN ["chmod", "+x", "./dependencies"]
RUN ["./dependencies"]
RUN ["chmod", "+x", "setup"]
RUN ["./setup"]
RUN ["cp", "-r", "conf", "/opt/digitalbits/conf"]
RUN ["crontab", "-u", "digitalbits", "/opt/digitalbits/conf/crontab.txt"]
RUN ["chmod", "+x", "start"]

ENTRYPOINT ["/src/ticker/services/ticker/docker/start"]
