#!/usr/bin/env bash
set -e

useradd --uid 10011001 --home-dir /home/digitalbits --no-log-init digitalbits \
    && mkdir -p /home/digitalbits \
    && chown -R digitalbits:digitalbits /home/digitalbits

mkdir -p /opt/digitalbits/bin
mkdir -p /opt/digitalbits/www
chown -R digitalbits:digitalbits /opt/digitalbits/www
mkdir -p /opt/digitalbits/postgresql/data
